language: python

python:
  - "3.6"
  - "3.7-dev"

services:
  - mysql

env:
  global:
    - DJANGO_SETTINGS_MODULE="travis_ci.settings"

branches:
  only:
    - master

install:
  - pip install -r requirements.txt

script:
  - python manage.py test