# Generated by Django 2.1.5 on 2019-03-01 13:39

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20190223_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
