# Generated by Django 2.1.7 on 2019-03-02 07:25

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_auto_20190301_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
    ]
