# Generated by Django 2.1.5 on 2019-02-20 12:45

import blogs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='description',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='pic',
            field=models.ImageField(default=None, upload_to=blogs.models.get_user_path),
        ),
    ]
