# Generated by Django 2.1.5 on 2019-03-01 04:42

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20190220_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='text',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
