# Generated by Django 2.1.7 on 2019-03-02 07:25

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20190301_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='text',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
    ]
